### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by wvdakker** [lifeofguenter/mu-conference#1]
Hi,

I am the maintainer of the jabber-muc package for Debian.
At this moment the development of mu-conference is stuck.
What is your plan with this repository?

I am trying to get jabber-muc into jabberd. Not sure if it will
work. A separate development is more wishful I guess.

/Willem

**Comment by lifeofguenter** [comment]
thanks @wvdakker for reaching out to me - I did not plan anything with mu-conference, and only created this repo as the original repository is down/offline.

I do not believe jabberd2 uses modern approaches of programming and such is relatively prone to errors + very fragile on libraries. This also means that jabberd2 will not be able to keep up with the pace that xmpp is introducing extensions to its protocol.

As such I switched over to prosody.im that has quite an active community. If you want, I can delete or transfer this repository :)

**Comment by wvdakker** [comment]
On Tue, 2018-01-02 at 04:36 -0800, Gunter Grodotzki wrote:
> thanks @wvdakker for reaching out to me - I did not plan anything
> with mu-conference, and only created this repo as the original
> repository is down/offline.
> 
> I do not believe jabberd2 uses modern approaches of programming and
> such is relatively prone to errors + very fragile on libraries. This
> also means that jabberd2 will not be able to keep up with the pace
> that xmpp is introducing extensions to its protocol.
> 
> As such I switched over to prosody.im that has quite an active
> community. If you want, I can delete or transfer this repository :)
> 
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 
> 
>   
>   
> 
> 
> 
> 
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
> 5493e4bb","name":"GitHub"},"entity":{"external_key":"github/lifeofgue
> nter/mu-conference","title":"lifeofguenter/mu-
> conference","subtitle":"GitHub repository","main_image_url":"https://
> cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-
> 11e6-95fc-
> 7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
> .com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
> b52498112777.png","action":{"name":"Open in GitHub","url":"https://gi
> thub.com/lifeofguenter/mu-
> conference"}},"updates":{"snippets":[{"icon":"PERSON","message":"@lif
> eofguenter in #1: thanks @wvdakker for reaching out to me - I did not
> plan anything with mu-conference, and only created this repo as the
> original repository is down/offline.\r\n\r\nI do not believe jabberd2
> uses modern approaches of programming and such is relatively prone to
> errors + very fragile on libraries. This also means that jabberd2
> will not be able to keep up with the pace that xmpp is introducing
> extensions to its protocol.\r\n\r\nAs such I switched over to
> prosody.im that has quite an active community. If you want, I can
> delete or transfer this repository :)"}],"action":{"name":"View
> Issue","url":"https://github.com/lifeofguenter/mu-conference/issues/1
> #issuecomment-354757989"}}}

Thanks,

What I dont like at Prosody is the LUA interface. Jabberd is a lean and
mean C interface.
You dont have to delete or transfer the repository.

/Willem
